package com.zipcodewilmington.jdbc.tools.database;

import com.zipcodewilmington.jdbc.tools.database.connection.ResultSetHandler;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;

public class DatabaseTest {
    private final Database database;

    public DatabaseTest() {
        this.database = Database.UAT;
        database.drop();
        database.create();
        database.use();
        database.disableLogging();
    }

    @Before
    public void setup() {
        try { // import sql-insert-statements
            MigrationsTable table = new MigrationsTable(database.getConnection());
            String localProjectRootDirectory = System.getProperty("user.dir");
            String localResourceDirectory = "/src/main/resources/migrations/uat/";
            table.importFilesFromPath(localProjectRootDirectory + localResourceDirectory);
        } catch (IOException e) {
        }
    }

    @Test
    public void getPokemonsTable() {
        String expected = "\n{name=Smeargle, secondary_type=null, primary_type=1, id=1}\n" +
                "{name=Wailord, secondary_type=null, primary_type=2, id=2}\n" +
                "{name=Vileplume, secondary_type=7, primary_type=3, id=3}\n" +
                "{name=Armaldo, secondary_type=8, primary_type=4, id=4}\n" +
                "{name=Cradily, secondary_type=3, primary_type=4, id=5}\n" +
                "{name=Carvanha, secondary_type=12, primary_type=2, id=6}\n" +
                "{name=Numel, secondary_type=6, primary_type=5, id=7}\n" +
                "{name=Sandslash, secondary_type=null, primary_type=6, id=8}\n" +
                "{name=Ninetales, secondary_type=null, primary_type=5, id=9}\n" +
                "{name=Weepinbell, secondary_type=7, primary_type=3, id=10}\n" +
                "{name=Gloom, secondary_type=7, primary_type=3, id=11}\n" +
                "{name=Ivysaur, secondary_type=7, primary_type=3, id=12}\n" +
                "{name=Nidorino, secondary_type=null, primary_type=7, id=13}\n" +
                "{name=Nidoking, secondary_type=6, primary_type=7, id=14}\n" +
                "{name=Dugtrio, secondary_type=null, primary_type=6, id=15}\n" +
                "{name=Rhyhorn, secondary_type=4, primary_type=6, id=16}\n" +
                "{name=Persian, secondary_type=null, primary_type=1, id=17}\n" +
                "{name=Wartortle, secondary_type=null, primary_type=2, id=18}\n" +
                "{name=Charmeleon, secondary_type=null, primary_type=5, id=19}\n" +
                "{name=Charizard, secondary_type=18, primary_type=5, id=20}\n" +
                "{name=Exeggutor, secondary_type=14, primary_type=3, id=21}\n" +
                "{name=Cloyster, secondary_type=17, primary_type=2, id=22}\n" +
                "{name=Arcanine, secondary_type=null, primary_type=5, id=23}\n" +
                "{name=Parasect, secondary_type=3, primary_type=8, id=24}\n" +
                "{name=Dewgong, secondary_type=17, primary_type=2, id=25}\n" +
                "{name=Chansey, secondary_type=null, primary_type=1, id=26}\n" +
                "{name=Kingler, secondary_type=null, primary_type=2, id=27}\n" +
                "{name=Tentacruel, secondary_type=7, primary_type=2, id=28}\n" +
                "{name=Blastoise, secondary_type=null, primary_type=2, id=29}\n" +
                "{name=Bellsprout, secondary_type=7, primary_type=3, id=30}\n" +
                "{name=Victreebel, secondary_type=7, primary_type=3, id=31}\n" +
                "{name=Rapidash, secondary_type=null, primary_type=5, id=32}\n" +
                "{name=Magneton, secondary_type=11, primary_type=9, id=33}\n" +
                "{name=Quagsire, secondary_type=6, primary_type=2, id=34}\n" +
                "{name=Exeggcute, secondary_type=14, primary_type=3, id=35}\n" +
                "{name=Horsea, secondary_type=null, primary_type=2, id=36}\n" +
                "{name=Electrode, secondary_type=null, primary_type=9, id=37}\n" +
                "{name=Starmie, secondary_type=14, primary_type=2, id=38}\n" +
                "{name=Seadra, secondary_type=null, primary_type=2, id=39}\n" +
                "{name=Butterfree, secondary_type=18, primary_type=8, id=40}\n" +
                "{name=Bellossom, secondary_type=null, primary_type=3, id=41}\n" +
                "{name=Dragonair, secondary_type=null, primary_type=10, id=42}\n" +
                "{name=Poliwhirl, secondary_type=null, primary_type=2, id=43}\n" +
                "{name=Flareon, secondary_type=null, primary_type=5, id=44}\n" +
                "{name=Eevee, secondary_type=null, primary_type=1, id=45}\n" +
                "{name=Vaporeon, secondary_type=null, primary_type=2, id=46}\n" +
                "{name=Jolteon, secondary_type=null, primary_type=9, id=47}\n" +
                "{name=Goldeen, secondary_type=null, primary_type=2, id=48}\n" +
                "{name=Seaking, secondary_type=null, primary_type=2, id=49}\n" +
                "{name=Golduck, secondary_type=null, primary_type=2, id=50}\n" +
                "{name=Staryu, secondary_type=null, primary_type=2, id=51}\n" +
                "{name=Pikachu, secondary_type=null, primary_type=9, id=52}\n" +
                "{name=Shellder, secondary_type=null, primary_type=2, id=53}\n" +
                "{name=Marill, secondary_type=16, primary_type=2, id=54}\n" +
                "{name=Skiploom, secondary_type=18, primary_type=3, id=55}\n" +
                "{name=Dratini, secondary_type=null, primary_type=10, id=56}\n" +
                "{name=Bulbasaur, secondary_type=7, primary_type=3, id=57}\n" +
                "{name=Venusaur, secondary_type=7, primary_type=3, id=58}\n" +
                "{name=Charmander, secondary_type=null, primary_type=5, id=59}\n" +
                "{name=Squirtle, secondary_type=null, primary_type=2, id=60}\n" +
                "{name=Nidoqueen, secondary_type=6, primary_type=7, id=61}\n" +
                "{name=Pidgeot, secondary_type=18, primary_type=1, id=62}\n" +
                "{name=Electabuzz, secondary_type=null, primary_type=9, id=63}\n" +
                "{name=Tangela, secondary_type=null, primary_type=3, id=64}\n" +
                "{name=Tauros, secondary_type=null, primary_type=1, id=65}\n" +
                "{name=Manectric, secondary_type=null, primary_type=9, id=66}\n" +
                "{name=Muk, secondary_type=null, primary_type=7, id=67}\n" +
                "{name=Azumarill, secondary_type=16, primary_type=2, id=68}\n" +
                "{name=Zangoose, secondary_type=null, primary_type=1, id=69}\n" +
                "{name=Wingull, secondary_type=18, primary_type=2, id=70}\n" +
                "{name=Roselia, secondary_type=7, primary_type=3, id=71}\n" +
                "{name=Pelipper, secondary_type=18, primary_type=2, id=72}\n" +
                "{name=Camerupt, secondary_type=6, primary_type=5, id=73}\n" +
                "{name=Mawile, secondary_type=16, primary_type=11, id=74}\n" +
                "{name=Sableye, secondary_type=15, primary_type=12, id=75}\n" +
                "{name=Swellow, secondary_type=18, primary_type=1, id=76}\n" +
                "{name=Trapinch, secondary_type=null, primary_type=6, id=77}\n" +
                "{name=Wailmer, secondary_type=null, primary_type=2, id=78}\n" +
                "{name=Shiftry, secondary_type=12, primary_type=3, id=79}\n" +
                "{name=Cacturne, secondary_type=12, primary_type=3, id=80}\n" +
                "{name=Lairon, secondary_type=4, primary_type=11, id=81}\n" +
                "{name=Linoone, secondary_type=null, primary_type=1, id=82}\n" +
                "{name=Milotic, secondary_type=null, primary_type=2, id=83}\n" +
                "{name=Delcatty, secondary_type=null, primary_type=1, id=84}\n" +
                "{name=Nosepass, secondary_type=null, primary_type=4, id=85}\n" +
                "{name=Medicham, secondary_type=14, primary_type=13, id=86}\n" +
                "{name=Ludicolo, secondary_type=3, primary_type=2, id=87}\n" +
                "{name=Kecleon, secondary_type=null, primary_type=1, id=88}\n" +
                "{name=Graveler, secondary_type=6, primary_type=4, id=89}\n" +
                "{name=Loudred, secondary_type=null, primary_type=1, id=90}\n" +
                "{name=Dodrio, secondary_type=18, primary_type=1, id=91}\n" +
                "{name=Kadabra, secondary_type=null, primary_type=14, id=92}\n" +
                "{name=Claydol, secondary_type=14, primary_type=6, id=93}\n" +
                "{name=Sharpedo, secondary_type=12, primary_type=2, id=94}\n" +
                "{name=Magcargo, secondary_type=4, primary_type=5, id=95}\n" +
                "{name=Electrike, secondary_type=null, primary_type=9, id=96}\n" +
                "{name=Makuhita, secondary_type=null, primary_type=13, id=97}\n" +
                "{name=Hariyama, secondary_type=null, primary_type=13, id=98}\n" +
                "{name=Wigglytuff, secondary_type=16, primary_type=1, id=99}\n" +
                "{name=Vigoroth, secondary_type=null, primary_type=1, id=100}\n" +
                "{name=Skarmory, secondary_type=18, primary_type=11, id=101}\n" +
                "{name=Spinda, secondary_type=null, primary_type=1, id=102}\n" +
                "{name=Exploud, secondary_type=null, primary_type=1, id=103}\n" +
                "{name=Slaking, secondary_type=null, primary_type=1, id=104}\n" +
                "{name=Lanturn, secondary_type=9, primary_type=2, id=105}\n" +
                "{name=Slakoth, secondary_type=null, primary_type=1, id=106}\n" +
                "{name=Absol, secondary_type=null, primary_type=12, id=107}\n" +
                "{name=Tropius, secondary_type=18, primary_type=3, id=108}\n" +
                "{name=Gardevoir, secondary_type=16, primary_type=14, id=109}\n" +
                "{name=Torkoal, secondary_type=null, primary_type=5, id=110}\n" +
                "{name=Lunatone, secondary_type=14, primary_type=4, id=111}\n" +
                "{name=Solrock, secondary_type=14, primary_type=4, id=112}\n" +
                "{name=Dusclops, secondary_type=null, primary_type=15, id=113}\n" +
                "{name=Tyranitar, secondary_type=12, primary_type=4, id=114}\n" +
                "{name=Clefairy, secondary_type=null, primary_type=16, id=115}\n" +
                "{name=Jigglypuff, secondary_type=16, primary_type=1, id=116}\n" +
                "{name=Kingdra, secondary_type=10, primary_type=2, id=117}\n" +
                "{name=Paras, secondary_type=3, primary_type=8, id=118}\n" +
                "{name=Lapras, secondary_type=17, primary_type=2, id=119}\n" +
                "{name=Rhydon, secondary_type=4, primary_type=6, id=120}\n" +
                "{name=Slowbro, secondary_type=14, primary_type=2, id=121}\n" +
                "{name=Ursaring, secondary_type=null, primary_type=1, id=122}\n" +
                "{name=Machoke, secondary_type=null, primary_type=13, id=123}\n" +
                "{name=Kangaskhan, secondary_type=null, primary_type=1, id=124}\n" +
                "{name=Machamp, secondary_type=null, primary_type=13, id=125}\n" +
                "{name=Oddish, secondary_type=7, primary_type=3, id=126}\n" +
                "{name=Girafarig, secondary_type=14, primary_type=1, id=127}\n" +
                "{name=Ponyta, secondary_type=null, primary_type=5, id=128}\n" +
                "{name=Vulpix, secondary_type=null, primary_type=5, id=129}\n" +
                "{name=Raticate, secondary_type=null, primary_type=1, id=130}\n" +
                "{name=Marowak, secondary_type=null, primary_type=6, id=131}\n" +
                "{name=Nidorina, secondary_type=null, primary_type=7, id=132}\n" +
                "{name=Onix, secondary_type=6, primary_type=4, id=133}\n" +
                "{name=Aerodactyl, secondary_type=18, primary_type=4, id=134}\n" +
                "{name=Sneasel, secondary_type=17, primary_type=12, id=135}\n" +
                "{name=Gastly, secondary_type=7, primary_type=15, id=136}\n" +
                "{name=Haunter, secondary_type=7, primary_type=15, id=137}\n" +
                "{name=Gengar, secondary_type=7, primary_type=15, id=138}\n" +
                "{name=Grotle, secondary_type=null, primary_type=3, id=139}\n" +
                "{name=Snover, secondary_type=17, primary_type=3, id=140}\n" +
                "{name=Ambipom, secondary_type=null, primary_type=1, id=141}\n" +
                "{name=Raichu, secondary_type=null, primary_type=9, id=142}\n" +
                "{name=Gastrodon, secondary_type=6, primary_type=2, id=143}\n" +
                "{name=Pachirisu, secondary_type=null, primary_type=9, id=144}\n" +
                "{name=Blissey, secondary_type=null, primary_type=1, id=145}\n" +
                "{name=Sudowoodo, secondary_type=null, primary_type=4, id=146}\n" +
                "{name=Misdreavus, secondary_type=null, primary_type=15, id=147}\n" +
                "{name=Drifblim, secondary_type=18, primary_type=15, id=148}\n" +
                "{name=Skorupi, secondary_type=8, primary_type=7, id=149}\n" +
                "{name=Steelix, secondary_type=6, primary_type=11, id=150}\n" +
                "{name=Lopunny, secondary_type=null, primary_type=1, id=151}\n" +
                "{name=Hippopotas, secondary_type=null, primary_type=6, id=152}\n" +
                "{name=Mightyena, secondary_type=null, primary_type=12, id=153}\n" +
                "{name=Kirlia, secondary_type=16, primary_type=14, id=154}\n" +
                "{name=Flaaffy, secondary_type=null, primary_type=9, id=155}\n" +
                "{name=Ampharos, secondary_type=null, primary_type=9, id=156}\n" +
                "{name=Monferno, secondary_type=13, primary_type=5, id=157}\n" +
                "{name=Gyarados, secondary_type=18, primary_type=2, id=158}\n" +
                "{name=Luxio, secondary_type=null, primary_type=9, id=159}\n" +
                "{name=Mothim, secondary_type=18, primary_type=8, id=160}\n" +
                "{name=Salamence, secondary_type=18, primary_type=10, id=161}\n" +
                "{name=Honchkrow, secondary_type=18, primary_type=12, id=162}\n" +
                "{name=Staravia, secondary_type=18, primary_type=1, id=163}\n" +
                "{name=Metagross, secondary_type=14, primary_type=11, id=164}\n" +
                "{name=Drapion, secondary_type=12, primary_type=7, id=165}\n" +
                "{name=Floatzel, secondary_type=null, primary_type=2, id=166}\n" +
                "{name=Stantler, secondary_type=null, primary_type=1, id=167}\n" +
                "{name=Carnivine, secondary_type=null, primary_type=3, id=168}\n" +
                "{name=Primeape, secondary_type=null, primary_type=13, id=169}\n" +
                "{name=Glameow, secondary_type=null, primary_type=1, id=170}\n" +
                "{name=Purugly, secondary_type=null, primary_type=1, id=171}\n" +
                "{name=Alakazam, secondary_type=null, primary_type=14, id=172}\n" +
                "{name=Yanma, secondary_type=18, primary_type=8, id=173}\n" +
                "{name=Bibarel, secondary_type=2, primary_type=1, id=174}\n" +
                "{name=Beautifly, secondary_type=18, primary_type=8, id=175}\n" +
                "{name=Meowth, secondary_type=null, primary_type=1, id=176}\n" +
                "{name=Hypno, secondary_type=null, primary_type=14, id=177}\n" +
                "{name=Dunsparce, secondary_type=null, primary_type=1, id=178}\n" +
                "{name=Scyther, secondary_type=18, primary_type=8, id=179}\n" +
                "{name=Rampardos, secondary_type=null, primary_type=4, id=180}\n" +
                "{name=Pinsir, secondary_type=null, primary_type=8, id=181}\n" +
                "{name=Lickitung, secondary_type=null, primary_type=1, id=182}\n" +
                "{name=Miltank, secondary_type=null, primary_type=1, id=183}\n" +
                "{name=Granbull, secondary_type=null, primary_type=16, id=184}\n" +
                "{name=Cherrim, secondary_type=null, primary_type=3, id=185}\n" +
                "{name=Larvitar, secondary_type=6, primary_type=4, id=186}\n" +
                "{name=Clefable, secondary_type=null, primary_type=16, id=187}\n" +
                "{name=Torterra, secondary_type=6, primary_type=3, id=188}\n" +
                "{name=Glalie, secondary_type=null, primary_type=17, id=189}\n" +
                "{name=Crobat, secondary_type=18, primary_type=7, id=190}\n" +
                "{name=Aipom, secondary_type=null, primary_type=1, id=191}\n" +
                "{name=Beedrill, secondary_type=7, primary_type=8, id=192}\n" +
                "{name=Porygon2, secondary_type=null, primary_type=1, id=193}\n" +
                "{name=Bronzor, secondary_type=14, primary_type=11, id=194}\n" +
                "{name=Snorunt, secondary_type=null, primary_type=17, id=195}\n" +
                "{name=Scizor, secondary_type=11, primary_type=8, id=196}\n" +
                "{name=Swalot, secondary_type=null, primary_type=7, id=197}\n" +
                "{name=Magnezone, secondary_type=11, primary_type=9, id=198}\n" +
                "{name=Magmar, secondary_type=null, primary_type=5, id=199}\n" +
                "{name=Electivire, secondary_type=null, primary_type=9, id=200}\n" +
                "{name=Magmortar, secondary_type=null, primary_type=5, id=201}\n" +
                "{name=Gligar, secondary_type=18, primary_type=6, id=202}\n" +
                "{name=Buizel, secondary_type=null, primary_type=2, id=203}\n" +
                "{name=Gliscor, secondary_type=18, primary_type=6, id=204}\n" +
                "{name=Probopass, secondary_type=11, primary_type=4, id=205}\n" +
                "{name=Tyrogue, secondary_type=null, primary_type=13, id=206}\n" +
                "{name=Hitmonchan, secondary_type=null, primary_type=13, id=207}\n" +
                "{name=Piloswine, secondary_type=6, primary_type=17, id=208}\n" +
                "{name=Staraptor, secondary_type=18, primary_type=1, id=209}\n" +
                "{name=Jumpluff, secondary_type=18, primary_type=3, id=210}\n" +
                "{name=Banette, secondary_type=null, primary_type=15, id=211}\n" +
                "{name=Ralts, secondary_type=16, primary_type=14, id=212}\n" +
                "{name=Roserade, secondary_type=7, primary_type=3, id=213}\n" +
                "{name=Lickilicky, secondary_type=null, primary_type=1, id=214}\n" +
                "{name=Abomasnow, secondary_type=17, primary_type=3, id=215}\n" +
                "{name=Metang, secondary_type=14, primary_type=11, id=216}\n" +
                "{name=Seviper, secondary_type=null, primary_type=7, id=217}\n" +
                "{name=Luxray, secondary_type=null, primary_type=9, id=218}\n" +
                "{name=Buneary, secondary_type=null, primary_type=1, id=219}\n" +
                "{name=Mamoswine, secondary_type=6, primary_type=17, id=220}\n" +
                "{name=Vibrava, secondary_type=10, primary_type=6, id=221}\n" +
                "{name=Flygon, secondary_type=10, primary_type=6, id=222}\n" +
                "{name=Nuzleaf, secondary_type=12, primary_type=3, id=223}\n" +
                "{name=Pupitar, secondary_type=6, primary_type=4, id=224}\n" +
                "{name=Magnemite, secondary_type=11, primary_type=9, id=225}\n" +
                "{name=Mareep, secondary_type=null, primary_type=9, id=226}\n" +
                "{name=Growlithe, secondary_type=null, primary_type=5, id=227}\n" +
                "{name=Slowking, secondary_type=14, primary_type=2, id=228}\n" +
                "{name=Drilbur, secondary_type=null, primary_type=6, id=229}\n" +
                "{name=Zebstrika, secondary_type=null, primary_type=9, id=230}\n" +
                "{name=Swoobat, secondary_type=18, primary_type=14, id=231}\n" +
                "{name=Stoutland, secondary_type=null, primary_type=1, id=232}\n" +
                "{name=Furret, secondary_type=null, primary_type=1, id=233}\n" +
                "{name=Gabite, secondary_type=6, primary_type=10, id=234}\n" +
                "{name=Grumpig, secondary_type=null, primary_type=14, id=235}\n" +
                "{name=Vanillish, secondary_type=null, primary_type=17, id=236}\n" +
                "{name=Gothorita, secondary_type=null, primary_type=14, id=237}\n" +
                "{name=Duosion, secondary_type=null, primary_type=14, id=238}\n" +
                "{name=Simisage, secondary_type=null, primary_type=3, id=239}\n" +
                "{name=Simisear, secondary_type=null, primary_type=5, id=240}\n" +
                "{name=Simipour, secondary_type=null, primary_type=2, id=241}\n" +
                "{name=Galvantula, secondary_type=9, primary_type=8, id=242}\n" +
                "{name=Sawsbuck, secondary_type=3, primary_type=1, id=243}\n" +
                "{name=Jellicent, secondary_type=15, primary_type=2, id=244}\n" +
                "{name=Fraxure, secondary_type=null, primary_type=10, id=245}\n" +
                "{name=Whimsicott, secondary_type=16, primary_type=3, id=246}\n" +
                "{name=Tirtouga, secondary_type=4, primary_type=2, id=247}\n" +
                "{name=Deino, secondary_type=10, primary_type=12, id=248}\n" +
                "{name=Druddigon, secondary_type=null, primary_type=10, id=249}\n" +
                "{name=Klang, secondary_type=null, primary_type=11, id=250}\n" +
                "{name=Seismitoad, secondary_type=6, primary_type=2, id=251}\n" +
                "{name=Scolipede, secondary_type=7, primary_type=8, id=252}\n" +
                "{name=Mienfoo, secondary_type=null, primary_type=13, id=253}\n" +
                "{name=Elgyem, secondary_type=null, primary_type=14, id=254}\n" +
                "{name=Pawniard, secondary_type=11, primary_type=12, id=255}\n" +
                "{name=Liepard, secondary_type=null, primary_type=12, id=256}\n" +
                "{name=Watchog, secondary_type=null, primary_type=1, id=257}\n" +
                "{name=Alomomola, secondary_type=null, primary_type=2, id=258}\n" +
                "{name=Klinklang, secondary_type=null, primary_type=11, id=259}\n" +
                "{name=Beheeyem, secondary_type=null, primary_type=14, id=260}\n" +
                "{name=Cubchoo, secondary_type=null, primary_type=17, id=261}\n" +
                "{name=Leavanny, secondary_type=3, primary_type=8, id=262}\n" +
                "{name=Archen, secondary_type=18, primary_type=4, id=263}\n" +
                "{name=Eelektrik, secondary_type=null, primary_type=9, id=264}\n" +
                "{name=Accelgor, secondary_type=null, primary_type=8, id=265}\n" +
                "{name=Espeon, secondary_type=null, primary_type=14, id=266}\n" +
                "{name=Walrein, secondary_type=2, primary_type=17, id=267}\n" +
                "{name=Gallade, secondary_type=13, primary_type=14, id=268}\n" +
                "{name=Jynx, secondary_type=14, primary_type=17, id=269}\n" +
                "{name=Rotom, secondary_type=15, primary_type=9, id=270}\n" +
                "{name=Gothita, secondary_type=null, primary_type=14, id=271}\n" +
                "{name=Lilligant, secondary_type=null, primary_type=3, id=272}\n" +
                "{name=Ducklett, secondary_type=18, primary_type=2, id=273}\n" +
                "{name=Krokorok, secondary_type=12, primary_type=6, id=274}\n" +
                "{name=Palpitoad, secondary_type=6, primary_type=2, id=275}\n" +
                "{name=Lampent, secondary_type=5, primary_type=15, id=276}\n" +
                "{name=Unfezant, secondary_type=18, primary_type=1, id=277}\n" +
                "{name=Axew, secondary_type=null, primary_type=10, id=278}\n" +
                "{name=Golurk, secondary_type=15, primary_type=6, id=279}\n" +
                "{name=Sigilyph, secondary_type=18, primary_type=14, id=280}\n" +
                "{name=Tangrowth, secondary_type=null, primary_type=3, id=281}\n" +
                "{name=Heatmor, secondary_type=null, primary_type=5, id=282}\n" +
                "{name=Umbreon, secondary_type=null, primary_type=12, id=283}\n" +
                "{name=Mismagius, secondary_type=null, primary_type=15, id=284}\n" +
                "{name=Klink, secondary_type=null, primary_type=11, id=285}\n" +
                "{name=Mantine, secondary_type=18, primary_type=2, id=286}\n" +
                "{name=Basculin, secondary_type=null, primary_type=2, id=287}\n" +
                "{name=Emolga, secondary_type=18, primary_type=9, id=288}\n" +
                "{name=Herdier, secondary_type=null, primary_type=1, id=289}\n" +
                "{name=Excadrill, secondary_type=11, primary_type=6, id=290}\n" +
                "{name=Swanna, secondary_type=18, primary_type=2, id=291}\n" +
                "{name=Mandibuzz, secondary_type=18, primary_type=12, id=292}\n" +
                "{name=Toxicroak, secondary_type=13, primary_type=7, id=293}\n" +
                "{name=Braviary, secondary_type=18, primary_type=1, id=294}\n" +
                "{name=Cofagrigus, secondary_type=null, primary_type=15, id=295}\n" +
                "{name=Beartic, secondary_type=null, primary_type=17, id=296}\n" +
                "{name=Durant, secondary_type=11, primary_type=8, id=297}\n" +
                "{name=Ferroseed, secondary_type=11, primary_type=3, id=298}\n" +
                "{name=Ferrothorn, secondary_type=11, primary_type=3, id=299}\n" +
                "{name=Lucario, secondary_type=11, primary_type=13, id=300}\n" +
                "{name=Weavile, secondary_type=17, primary_type=12, id=301}\n" +
                "{name=Weezing, secondary_type=null, primary_type=7, id=302}\n" +
                "{name=Bronzong, secondary_type=14, primary_type=11, id=303}\n" +
                "{name=Eelektross, secondary_type=null, primary_type=9, id=304}\n" +
                "{name=Doublade, secondary_type=15, primary_type=11, id=305}\n" +
                "{name=Chandelure, secondary_type=5, primary_type=15, id=306}\n" +
                "{name=Crustle, secondary_type=4, primary_type=8, id=307}\n" +
                "{name=Doduo, secondary_type=18, primary_type=1, id=308}\n" +
                "{name=Helioptile, secondary_type=1, primary_type=9, id=309}\n" +
                "{name=Carbink, secondary_type=16, primary_type=4, id=310}\n" +
                "{name=Cryogonal, secondary_type=null, primary_type=17, id=311}\n" +
                "{name=Vanilluxe, secondary_type=null, primary_type=17, id=312}\n" +
                "{name=Delibird, secondary_type=18, primary_type=17, id=313}\n" +
                "{name=Rhyperior, secondary_type=4, primary_type=6, id=314}\n" +
                "{name=Masquerain, secondary_type=18, primary_type=8, id=315}\n" +
                "{name=Golem, secondary_type=6, primary_type=4, id=316}\n" +
                "{name=Froslass, secondary_type=15, primary_type=17, id=317}\n" +
                "{name=Shedinja, secondary_type=15, primary_type=8, id=318}\n" +
                "{name=Breloom, secondary_type=13, primary_type=3, id=319}\n" +
                "{name=Bagon, secondary_type=null, primary_type=10, id=320}\n" +
                "{name=Talonflame, secondary_type=18, primary_type=5, id=321}\n" +
                "{name=Haxorus, secondary_type=null, primary_type=10, id=322}\n" +
                "{name=Slugma, secondary_type=null, primary_type=5, id=323}\n" +
                "{name=Goomy, secondary_type=null, primary_type=10, id=324}\n" +
                "{name=Sylveon, secondary_type=null, primary_type=16, id=325}\n" +
                "{name=Grimer, secondary_type=null, primary_type=7, id=326}\n" +
                "{name=Goodra, secondary_type=null, primary_type=10, id=327}\n" +
                "{name=Fearow, secondary_type=18, primary_type=1, id=328}\n" +
                "{name=Garbodor, secondary_type=null, primary_type=7, id=329}\n" +
                "{name=Slowpoke, secondary_type=14, primary_type=2, id=330}\n" +
                "{name=Sandshrew, secondary_type=null, primary_type=6, id=331}\n" +
                "{name=Psyduck, secondary_type=null, primary_type=2, id=332}\n" +
                "{name=Poliwag, secondary_type=null, primary_type=2, id=333}\n" +
                "{name=Diglett, secondary_type=null, primary_type=6, id=334}\n" +
                "{name=Seel, secondary_type=null, primary_type=2, id=335}\n" +
                "{name=Voltorb, secondary_type=null, primary_type=9, id=336}\n" +
                "{name=Ditto, secondary_type=null, primary_type=1, id=337}\n" +
                "{name=Koffing, secondary_type=null, primary_type=7, id=338}\n" +
                "{name=Moltres, secondary_type=18, primary_type=5, id=339}\n" +
                "{name=Kabutops, secondary_type=2, primary_type=4, id=340}\n" +
                "{name=Dragonite, secondary_type=18, primary_type=10, id=341}\n" +
                "{name=Snorlax, secondary_type=null, primary_type=1, id=342}\n" +
                "{name=Omastar, secondary_type=2, primary_type=4, id=343}\n" +
                "{name=Poliwrath, secondary_type=13, primary_type=2, id=344}\n" +
                "{name=Mew, secondary_type=null, primary_type=14, id=345}\n" +
                "{name=Zapdos, secondary_type=18, primary_type=9, id=346}\n" +
                "{name=Remoraid, secondary_type=null, primary_type=2, id=347}\n" +
                "{name=Politoed, secondary_type=null, primary_type=2, id=348}\n" +
                "{name=Venonat, secondary_type=7, primary_type=8, id=349}\n" +
                "{name=Celebi, secondary_type=3, primary_type=14, id=350}\n" +
                "{name=Raikou, secondary_type=null, primary_type=9, id=351}\n" +
                "{name=Chikorita, secondary_type=null, primary_type=3, id=352}\n" +
                "{name=Totodile, secondary_type=null, primary_type=2, id=353}\n" +
                "{name=Cyndaquil, secondary_type=null, primary_type=5, id=354}\n" +
                "{name=Bayleef, secondary_type=null, primary_type=3, id=355}\n" +
                "{name=Croconaw, secondary_type=null, primary_type=2, id=356}\n" +
                "{name=Quilava, secondary_type=null, primary_type=5, id=357}\n" +
                "{name=Anorith, secondary_type=8, primary_type=4, id=358}\n" +
                "{name=Sunkern, secondary_type=null, primary_type=3, id=359}\n" +
                "{name=Hoppip, secondary_type=18, primary_type=3, id=360}\n" +
                "{name=Luvdisc, secondary_type=null, primary_type=2, id=361}\n" +
                "{name=Hoothoot, secondary_type=18, primary_type=1, id=362}\n" +
                "{name=Treecko, secondary_type=null, primary_type=3, id=363}\n" +
                "{name=Sunflora, secondary_type=null, primary_type=3, id=364}\n" +
                "{name=Taillow, secondary_type=18, primary_type=1, id=365}\n" +
                "{name=Togepi, secondary_type=null, primary_type=16, id=366}\n" +
                "{name=Surskit, secondary_type=2, primary_type=8, id=367}\n" +
                "{name=Blaziken, secondary_type=13, primary_type=5, id=368}\n" +
                "{name=Sceptile, secondary_type=null, primary_type=3, id=369}\n" +
                "{name=Swampert, secondary_type=6, primary_type=2, id=370}\n" +
                "{name=Altaria, secondary_type=18, primary_type=10, id=371}\n" +
                "{name=Mudkip, secondary_type=null, primary_type=2, id=372}\n" +
                "{name=Zubat, secondary_type=18, primary_type=7, id=373}\n" +
                "{name=Cacnea, secondary_type=null, primary_type=3, id=374}\n" +
                "{name=Barboach, secondary_type=6, primary_type=2, id=375}\n" +
                "{name=Seedot, secondary_type=null, primary_type=3, id=376}\n" +
                "{name=Typhlosion, secondary_type=null, primary_type=5, id=377}\n" +
                "{name=Feraligatr, secondary_type=null, primary_type=2, id=378}\n" +
                "{name=Meganium, secondary_type=null, primary_type=3, id=379}\n" +
                "{name=Jirachi, secondary_type=14, primary_type=11, id=380}\n" +
                "{name=Xatu, secondary_type=18, primary_type=14, id=381}\n" +
                "{name=Latias, secondary_type=14, primary_type=10, id=382}\n" +
                "{name=Illumise, secondary_type=null, primary_type=8, id=383}\n" +
                "{name=Entei, secondary_type=null, primary_type=5, id=384}\n" +
                "{name=Gorebyss, secondary_type=null, primary_type=2, id=385}\n" +
                "{name=Suicune, secondary_type=null, primary_type=2, id=386}\n" +
                "{name=Aggron, secondary_type=4, primary_type=11, id=387}\n" +
                "{name=Donphan, secondary_type=null, primary_type=6, id=388}\n" +
                "{name=Golbat, secondary_type=18, primary_type=7, id=389}\n" +
                "{name=Noctowl, secondary_type=18, primary_type=1, id=390}\n" +
                "{name=Forretress, secondary_type=11, primary_type=8, id=391}\n" +
                "{name=Houndoom, secondary_type=5, primary_type=12, id=392}\n" +
                "{name=Castform, secondary_type=null, primary_type=1, id=393}\n" +
                "{name=Rayquaza, secondary_type=18, primary_type=10, id=394}\n" +
                "{name=Huntail, secondary_type=null, primary_type=2, id=395}\n" +
                "{name=Volbeat, secondary_type=null, primary_type=8, id=396}\n" +
                "{name=Dustox, secondary_type=7, primary_type=8, id=397}\n" +
                "{name=Ledian, secondary_type=18, primary_type=8, id=398}\n" +
                "{name=Ariados, secondary_type=7, primary_type=8, id=399}\n" +
                "{name=Relicanth, secondary_type=4, primary_type=2, id=400}\n" +
                "{name=Octillery, secondary_type=null, primary_type=2, id=401}\n" +
                "{name=Lombre, secondary_type=3, primary_type=2, id=402}\n" +
                "{name=Clamperl, secondary_type=null, primary_type=2, id=403}\n" +
                "{name=Teddiursa, secondary_type=null, primary_type=1, id=404}\n" +
                "{name=Nincada, secondary_type=6, primary_type=8, id=405}\n" +
                "{name=Swinub, secondary_type=6, primary_type=17, id=406}\n" +
                "{name=Sentret, secondary_type=null, primary_type=1, id=407}\n" +
                "{name=Pineco, secondary_type=null, primary_type=8, id=408}\n" +
                "{name=Skitty, secondary_type=null, primary_type=1, id=409}\n" +
                "{name=Zigzagoon, secondary_type=null, primary_type=1, id=410}\n" +
                "{name=Heracross, secondary_type=13, primary_type=8, id=411}\n" +
                "{name=Wobbuffet, secondary_type=null, primary_type=14, id=412}\n" +
                "{name=Regice, secondary_type=null, primary_type=17, id=413}\n" +
                "{name=Swablu, secondary_type=18, primary_type=1, id=414}\n" +
                "{name=Plusle, secondary_type=null, primary_type=9, id=415}\n" +
                "{name=Minun, secondary_type=null, primary_type=9, id=416}\n" +
                "{name=Spoink, secondary_type=null, primary_type=14, id=417}\n" +
                "{name=Qwilfish, secondary_type=7, primary_type=2, id=418}\n" +
                "{name=Combusken, secondary_type=13, primary_type=5, id=419}\n" +
                "{name=Azurill, secondary_type=16, primary_type=1, id=420}\n" +
                "{name=Igglybuff, secondary_type=16, primary_type=1, id=421}\n" +
                "{name=Togetic, secondary_type=18, primary_type=16, id=422}\n" +
                "{name=Corsola, secondary_type=4, primary_type=2, id=423}\n" +
                "{name=Baltoy, secondary_type=14, primary_type=6, id=424}\n" +
                "{name=Articuno, secondary_type=18, primary_type=17, id=425}\n" +
                "{name=Lileep, secondary_type=3, primary_type=4, id=426}\n" +
                "{name=Chimecho, secondary_type=null, primary_type=14, id=427}\n" +
                "{name=Murkrow, secondary_type=18, primary_type=12, id=428}\n" +
                "{name=Sealeo, secondary_type=2, primary_type=17, id=429}\n" +
                "{name=Ledyba, secondary_type=18, primary_type=8, id=430}\n" +
                "{name=Sliggoo, secondary_type=null, primary_type=10, id=431}\n" +
                "{name=Lumineon, secondary_type=null, primary_type=2, id=432}\n" +
                "{name=Shelgon, secondary_type=null, primary_type=10, id=433}\n" +
                "{name=Poochyena, secondary_type=null, primary_type=12, id=434}\n" +
                "{name=Corphish, secondary_type=null, primary_type=2, id=435}\n" +
                "{name=Phanpy, secondary_type=null, primary_type=6, id=436}\n" +
                "{name=Whismur, secondary_type=null, primary_type=1, id=437}\n" +
                "{name=Regirock, secondary_type=null, primary_type=4, id=438}\n" +
                "{name=Registeel, secondary_type=null, primary_type=11, id=439}\n" +
                "{name=Groudon, secondary_type=null, primary_type=6, id=440}\n" +
                "{name=Shuckle, secondary_type=4, primary_type=8, id=441}\n" +
                "{name=Hitmontop, secondary_type=null, primary_type=13, id=442}\n" +
                "{name=Geodude, secondary_type=6, primary_type=4, id=443}\n" +
                "{name=Grovyle, secondary_type=null, primary_type=3, id=444}\n" +
                "{name=Marshtomp, secondary_type=6, primary_type=2, id=445}\n" +
                "{name=Beldum, secondary_type=14, primary_type=11, id=446}\n" +
                "{name=Wynaut, secondary_type=null, primary_type=14, id=447}\n" +
                "{name=Lotad, secondary_type=3, primary_type=2, id=448}\n" +
                "{name=Machop, secondary_type=null, primary_type=13, id=449}\n" +
                "{name=Shroomish, secondary_type=null, primary_type=3, id=450}\n" +
                "{name=Turtwig, secondary_type=null, primary_type=3, id=451}\n" +
                "{name=Budew, secondary_type=7, primary_type=3, id=452}\n" +
                "{name=Combee, secondary_type=18, primary_type=8, id=453}\n" +
                "{name=Cherubi, secondary_type=null, primary_type=3, id=454}\n" +
                "{name=Gogoat, secondary_type=null, primary_type=3, id=455}\n" +
                "{name=Bonsly, secondary_type=null, primary_type=4, id=456}\n" +
                "{name=Kricketune, secondary_type=null, primary_type=8, id=457}\n" +
                "{name=Abra, secondary_type=null, primary_type=14, id=458}\n" +
                "{name=Ninjask, secondary_type=18, primary_type=8, id=459}\n" +
                "{name=Wooper, secondary_type=6, primary_type=2, id=460}\n" +
                "{name=Latios, secondary_type=14, primary_type=10, id=461}\n" +
                "{name=Natu, secondary_type=18, primary_type=14, id=462}\n" +
                "{name=Spheal, secondary_type=2, primary_type=17, id=463}\n" +
                "{name=Whiscash, secondary_type=6, primary_type=2, id=464}\n" +
                "{name=Shuppet, secondary_type=null, primary_type=15, id=465}\n" +
                "{name=Meditite, secondary_type=14, primary_type=13, id=466}\n" +
                "{name=Cascoon, secondary_type=null, primary_type=8, id=467}\n" +
                "{name=Feebas, secondary_type=null, primary_type=2, id=468}\n" +
                "{name=Chinchou, secondary_type=9, primary_type=2, id=469}\n" +
                "{name=Aron, secondary_type=4, primary_type=11, id=470}\n" +
                "{name=Torchic, secondary_type=null, primary_type=5, id=471}\n" +
                "{name=Fletchinder, secondary_type=18, primary_type=5, id=472}\n" +
                "{name=Bisharp, secondary_type=11, primary_type=12, id=473}\n" +
                "{name=Pansear, secondary_type=null, primary_type=5, id=474}\n" +
                "{name=Panpour, secondary_type=null, primary_type=2, id=475}\n" +
                "{name=Sawk, secondary_type=null, primary_type=13, id=476}\n" +
                "{name=Throh, secondary_type=null, primary_type=13, id=477}\n" +
                "{name=Darumaka, secondary_type=null, primary_type=5, id=478}\n" +
                "{name=Bouffalant, secondary_type=null, primary_type=1, id=479}\n" +
                "{name=Boldore, secondary_type=null, primary_type=4, id=480}\n" +
                "{name=Gigalith, secondary_type=null, primary_type=4, id=481}\n" +
                "{name=Minccino, secondary_type=null, primary_type=1, id=482}\n" +
                "{name=Scraggy, secondary_type=13, primary_type=12, id=483}\n" +
                "{name=Cottonee, secondary_type=16, primary_type=3, id=484}\n" +
                "{name=Maractus, secondary_type=null, primary_type=3, id=485}\n" +
                "{name=Porygon-Z, secondary_type=null, primary_type=1, id=486}\n" +
                "{name=Pidove, secondary_type=18, primary_type=1, id=487}\n" +
                "{name=Petilil, secondary_type=null, primary_type=3, id=488}\n" +
                "{name=Tranquill, secondary_type=18, primary_type=1, id=489}\n" +
                "{name=Munna, secondary_type=null, primary_type=14, id=490}\n" +
                "{name=Swadloon, secondary_type=3, primary_type=8, id=491}\n" +
                "{name=Dwebble, secondary_type=4, primary_type=8, id=492}\n" +
                "{name=Croagunk, secondary_type=13, primary_type=7, id=493}\n" +
                "{name=Blitzle, secondary_type=null, primary_type=9, id=494}\n" +
                "{name=Sandile, secondary_type=12, primary_type=6, id=495}\n" +
                "{name=Cubone, secondary_type=null, primary_type=6, id=496}\n" +
                "{name=Omanyte, secondary_type=2, primary_type=4, id=497}\n" +
                "{name=Shieldon, secondary_type=11, primary_type=4, id=498}\n" +
                "{name=Archeops, secondary_type=18, primary_type=4, id=499}\n" +
                "{name=Mantyke, secondary_type=18, primary_type=2, id=500}\n" +
                "{name=Vanillite, secondary_type=null, primary_type=17, id=501}\n" +
                "{name=Woobat, secondary_type=18, primary_type=14, id=502}\n" +
                "{name=Riolu, secondary_type=null, primary_type=13, id=503}\n" +
                "{name=Timburr, secondary_type=null, primary_type=13, id=504}\n" +
                "{name=Kabuto, secondary_type=2, primary_type=4, id=505}\n" +
                "{name=Cranidos, secondary_type=null, primary_type=4, id=506}\n" +
                "{name=Carracosta, secondary_type=4, primary_type=2, id=507}\n" +
                "{name=Fletchling, secondary_type=18, primary_type=1, id=508}\n" +
                "{name=Bunnelby, secondary_type=null, primary_type=1, id=509}\n" +
                "{name=Pansage, secondary_type=null, primary_type=3, id=510}\n" +
                "{name=Tentacool, secondary_type=7, primary_type=2, id=511}\n" +
                "{name=Snubbull, secondary_type=null, primary_type=16, id=512}\n" +
                "{name=Houndour, secondary_type=5, primary_type=12, id=513}\n" +
                "{name=Clauncher, secondary_type=null, primary_type=2, id=514}\n" +
                "{name=Scatterbug, secondary_type=null, primary_type=8, id=515}\n" +
                "{name=Burmy, secondary_type=null, primary_type=8, id=516}\n" +
                "{name=Bidoof, secondary_type=null, primary_type=1, id=517}\n" +
                "{name=Dragalge, secondary_type=10, primary_type=7, id=518}\n" +
                "{name=Klefki, secondary_type=16, primary_type=11, id=519}\n" +
                "{name=Cobalion, secondary_type=13, primary_type=11, id=520}\n" +
                "{name=Terrakion, secondary_type=13, primary_type=4, id=521}\n" +
                "{name=Virizion, secondary_type=13, primary_type=3, id=522}\n" +
                "{name=Scrafty, secondary_type=13, primary_type=12, id=523}\n" +
                "{name=Gurdurr, secondary_type=null, primary_type=13, id=524}\n" +
                "{name=Mienshao, secondary_type=null, primary_type=13, id=525}\n" +
                "{name=Hitmonlee, secondary_type=null, primary_type=13, id=526}\n" +
                "{name=Conkeldurr, secondary_type=null, primary_type=13, id=527}\n" +
                "{name=Hawlucha, secondary_type=18, primary_type=13, id=528}\n" +
                "{name=Rattata, secondary_type=null, primary_type=1, id=529}\n" +
                "{name=Pidgeotto, secondary_type=18, primary_type=1, id=530}\n" +
                "{name=Finneon, secondary_type=null, primary_type=2, id=531}\n" +
                "{name=Elekid, secondary_type=null, primary_type=9, id=532}\n" +
                "{name=Espurr, secondary_type=null, primary_type=14, id=533}\n" +
                "{name=Krookodile, secondary_type=12, primary_type=6, id=534}\n" +
                "{name=Krabby, secondary_type=null, primary_type=2, id=535}\n" +
                "{name=Pidgey, secondary_type=18, primary_type=1, id=536}\n" +
                "{name=Wurmple, secondary_type=null, primary_type=8, id=537}\n" +
                "{name=Crawdaunt, secondary_type=12, primary_type=2, id=538}\n" +
                "{name=Stunky, secondary_type=12, primary_type=7, id=539}\n" +
                "{name=Drifloon, secondary_type=18, primary_type=15, id=540}\n" +
                "{name=Magby, secondary_type=null, primary_type=5, id=541}\n" +
                "{name=Gulpin, secondary_type=null, primary_type=7, id=542}\n" +
                "{name=Arbok, secondary_type=null, primary_type=7, id=543}\n" +
                "{name=Joltik, secondary_type=9, primary_type=8, id=544}\n" +
                "{name=Ekans, secondary_type=null, primary_type=7, id=545}\n" +
                "{name=Mankey, secondary_type=null, primary_type=13, id=546}\n" +
                "{name=Venomoth, secondary_type=7, primary_type=8, id=547}\n" +
                "{name=Spearow, secondary_type=18, primary_type=1, id=548}\n" +
                "{name=Starly, secondary_type=18, primary_type=1, id=549}\n" +
                "{name=Infernape, secondary_type=13, primary_type=5, id=550}\n" +
                "{name=Roggenrola, secondary_type=null, primary_type=4, id=551}\n" +
                "{name=Pangoro, secondary_type=12, primary_type=13, id=552}\n" +
                "{name=Smoochum, secondary_type=14, primary_type=17, id=553}\n" +
                "{name=Kyogre, secondary_type=null, primary_type=2, id=554}\n" +
                "{name=Silcoon, secondary_type=null, primary_type=8, id=555}\n" +
                "{name=Mewtwo, secondary_type=null, primary_type=14, id=556}\n" +
                "{name=Golett, secondary_type=15, primary_type=6, id=557}\n" +
                "{name=Garchomp, secondary_type=6, primary_type=10, id=558}\n" +
                "{name=Volcarona, secondary_type=5, primary_type=8, id=559}\n" +
                "{name=Audino, secondary_type=null, primary_type=1, id=560}\n" +
                "{name=Togekiss, secondary_type=18, primary_type=16, id=561}\n" +
                "{name=Dusknoir, secondary_type=null, primary_type=15, id=562}\n" +
                "{name=Hydreigon, secondary_type=10, primary_type=12, id=563}\n" +
                "{name=Heatran, secondary_type=11, primary_type=5, id=564}\n" +
                "{name=Cresselia, secondary_type=null, primary_type=14, id=565}\n" +
                "{name=Musharna, secondary_type=null, primary_type=14, id=566}\n" +
                "{name=Weedle, secondary_type=7, primary_type=8, id=567}\n" +
                "{name=Caterpie, secondary_type=null, primary_type=8, id=568}\n" +
                "{name=Kakuna, secondary_type=7, primary_type=8, id=569}\n" +
                "{name=Metapod, secondary_type=null, primary_type=8, id=570}\n" +
                "{name=Kricketot, secondary_type=null, primary_type=8, id=571}\n" +
                "{name=Magikarp, secondary_type=null, primary_type=2, id=572}\n" +
                "{name=Spinarak, secondary_type=7, primary_type=8, id=573}\n" +
                "{name=Vespiquen, secondary_type=18, primary_type=8, id=574}\n" +
                "{name=Drowzee, secondary_type=null, primary_type=14, id=575}\n" +
                "{name=Shinx, secondary_type=null, primary_type=9, id=576}\n" +
                "{name=Chimchar, secondary_type=null, primary_type=5, id=577}\n" +
                "{name=Skuntank, secondary_type=12, primary_type=7, id=578}\n" +
                "{name=Sewaddle, secondary_type=3, primary_type=8, id=579}\n" +
                "{name=Cleffa, secondary_type=null, primary_type=16, id=580}\n" +
                "{name=Pichu, secondary_type=null, primary_type=9, id=581}\n" +
                "{name=Duskull, secondary_type=null, primary_type=15, id=582}\n" +
                "{name=Unown, secondary_type=null, primary_type=14, id=583}\n" +
                "{name=Munchlax, secondary_type=null, primary_type=1, id=584}\n" +
                "{name=Porygon, secondary_type=null, primary_type=1, id=585}\n" +
                "{name=Gible, secondary_type=6, primary_type=10, id=586}\n" +
                "{name=Prinplup, secondary_type=null, primary_type=2, id=587}\n" +
                "{name=Whirlipede, secondary_type=7, primary_type=8, id=588}\n" +
                "{name=Noivern, secondary_type=10, primary_type=18, id=589}\n" +
                "{name=Pyroar, secondary_type=1, primary_type=5, id=590}\n" +
                "{name=Florges, secondary_type=null, primary_type=16, id=591}\n" +
                "{name=Clawitzer, secondary_type=null, primary_type=2, id=592}\n" +
                "{name=Barbaracle, secondary_type=2, primary_type=4, id=593}\n" +
                "{name=Dedenne, secondary_type=16, primary_type=9, id=594}\n" +
                "{name=Floette, secondary_type=null, primary_type=16, id=595}\n" +
                "{name=Slurpuff, secondary_type=null, primary_type=16, id=596}\n" +
                "{name=Aromatisse, secondary_type=null, primary_type=16, id=597}\n" +
                "{name=Shellos, secondary_type=null, primary_type=2, id=598}\n" +
                "{name=Stunfisk, secondary_type=9, primary_type=6, id=599}\n" +
                "{name=Frillish, secondary_type=15, primary_type=2, id=600}\n" +
                "{name=Hippowdon, secondary_type=null, primary_type=6, id=601}\n" +
                "{name=Chatot, secondary_type=18, primary_type=1, id=602}\n" +
                "{name=Lillipup, secondary_type=null, primary_type=1, id=603}\n" +
                "{name=Venipede, secondary_type=7, primary_type=8, id=604}\n" +
                "{name=Bastiodon, secondary_type=11, primary_type=4, id=605}\n" +
                "{name=Tynamo, secondary_type=null, primary_type=9, id=606}\n" +
                "{name=Diggersby, secondary_type=6, primary_type=1, id=607}\n" +
                "{name=Chingling, secondary_type=null, primary_type=14, id=608}\n" +
                "{name=Trubbish, secondary_type=null, primary_type=7, id=609}\n" +
                "{name=Cinccino, secondary_type=null, primary_type=1, id=610}\n" +
                "{name=Glaceon, secondary_type=null, primary_type=17, id=611}\n" +
                "{name=Leafeon, secondary_type=null, primary_type=3, id=612}\n" +
                "{name=Regigigas, secondary_type=null, primary_type=1, id=613}\n" +
                "{name=Purrloin, secondary_type=null, primary_type=12, id=614}\n" +
                "{name=Nidoran, secondary_type=null, primary_type=7, id=615}\n" +
                "{name=Deerling, secondary_type=3, primary_type=1, id=616}\n" +
                "{name=Shelmet, secondary_type=null, primary_type=8, id=617}\n" +
                "{name=Patrat, secondary_type=null, primary_type=1, id=618}\n" +
                "{name=Escavalier, secondary_type=11, primary_type=8, id=619}\n" +
                "{name=Avalugg, secondary_type=null, primary_type=17, id=620}\n" +
                "{name=Vivillon, secondary_type=18, primary_type=8, id=621}\n" +
                "{name=Heliolisk, secondary_type=1, primary_type=9, id=622}\n" +
                "{name=Aurorus, secondary_type=17, primary_type=4, id=623}\n" +
                "{name=Tyrantrum, secondary_type=10, primary_type=4, id=624}\n" +
                "{name=Yanmega, secondary_type=18, primary_type=8, id=625}\n" +
                "{name=Spiritomb, secondary_type=12, primary_type=15, id=626}\n" +
                "{name=Vullaby, secondary_type=18, primary_type=12, id=627}\n" +
                "{name=Zoroark, secondary_type=null, primary_type=12, id=628}\n" +
                "{name=Amoonguss, secondary_type=7, primary_type=3, id=629}\n" +
                "{name=Tympole, secondary_type=null, primary_type=2, id=630}\n" +
                "{name=Piplup, secondary_type=null, primary_type=2, id=631}\n" +
                "{name=Empoleon, secondary_type=11, primary_type=2, id=632}\n" +
                "{name=Furfrou, secondary_type=null, primary_type=1, id=633}\n" +
                "{name=Solosis, secondary_type=null, primary_type=14, id=634}\n" +
                "{name=Larvesta, secondary_type=5, primary_type=8, id=635}\n" +
                "{name=Foongus, secondary_type=7, primary_type=3, id=636}\n" +
                "{name=Litwick, secondary_type=5, primary_type=15, id=637}\n" +
                "{name=Yamask, secondary_type=null, primary_type=15, id=638}\n" +
                "{name=Gothitelle, secondary_type=null, primary_type=14, id=639}\n" +
                "{name=Reuniclus, secondary_type=null, primary_type=14, id=640}\n" +
                "{name=Pancham, secondary_type=null, primary_type=13, id=641}\n" +
                "{name=Litleo, secondary_type=1, primary_type=5, id=642}\n" +
                "{name=Skiddo, secondary_type=null, primary_type=3, id=643}\n" +
                "{name=Rufflet, secondary_type=18, primary_type=1, id=644}\n" +
                "{name=Karrablast, secondary_type=null, primary_type=8, id=645}\n" +
                "{name=Lugia, secondary_type=18, primary_type=14, id=646}\n" +
                "{name=Binacle, secondary_type=2, primary_type=4, id=647}\n" +
                "{name=Skrelp, secondary_type=2, primary_type=7, id=648}\n" +
                "{name=Malamar, secondary_type=14, primary_type=12, id=649}\n" +
                "{name=Zekrom, secondary_type=9, primary_type=10, id=650}\n" +
                "{name=Reshiram, secondary_type=5, primary_type=10, id=651}\n" +
                "{name=Happiny, secondary_type=null, primary_type=1, id=652}\n" +
                "{name=Zweilous, secondary_type=10, primary_type=12, id=653}\n" +
                "{name=Trevenant, secondary_type=3, primary_type=15, id=654}\n" +
                "{name=Swirlix, secondary_type=null, primary_type=16, id=655}\n" +
                "{name=Spewpa, secondary_type=null, primary_type=8, id=656}";

        // Then
        DatabaseTable pokemons = database.getTable("pokemons");
        ResultSetHandler rsh = pokemons.select("*");

        Assert.assertEquals(expected, rsh.toString());

    }
}
